# Generated by Django 4.2.2 on 2023-07-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='color',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='measurement',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=''),
        ),
    ]
