# Generated by Django 4.2.2 on 2023-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_color_stock_measurement_alter_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='color',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='measurement',
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
