# Generated by Django 4.2.2 on 2023-07-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stock_color_remove_stock_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='color',
            field=models.CharField(default='', max_length=30),
        ),
    ]
