# Generated by Django 4.2.2 on 2023-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='units',
            field=models.CharField(default='', max_length=30),
        ),
    ]
