# Generated by Django 4.2.2 on 2023-07-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='size',
            field=models.CharField(default='', max_length=30),
        ),
    ]
