# Generated by Django 4.2.2 on 2023-07-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_accessories_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='color',
        ),
        migrations.AddField(
            model_name='accessories',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accessories',
            name='receive',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='receive',
            field=models.CharField(default='', max_length=50),
        ),
    ]
