# Generated by Django 4.2.2 on 2023-07-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_stock_color_accessories_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='code',
            new_name='value',
        ),
        migrations.AddField(
            model_name='accessories',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='value',
            field=models.CharField(default='', max_length=30),
        ),
    ]
