# Generated by Django 4.2.2 on 2023-07-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_code_accessories_value_accessories_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='date',
            new_name='time',
        ),
    ]
