# Generated by Django 4.2.2 on 2023-07-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_date_accessories_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='time',
        ),
    ]
