# Generated by Django 4.2.2 on 2023-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_date_stock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
