# Generated by Django 4.2.2 on 2023-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
