# Generated by Django 4.2.2 on 2023-07-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='materialPerProduct',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='materialQty',
        ),
    ]
