# Generated by Django 4.2.2 on 2023-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_saleitem_materialperproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='pqty',
            field=models.IntegerField(default=1),
        ),
    ]
