# Generated by Django 4.2.2 on 2023-07-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_salebilldetails_id_alter_salebill_billno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salebill',
            old_name='kra',
            new_name='mode',
        ),
    ]
