# Generated by Django 4.2.2 on 2023-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_salebill_deliverydate_alter_salebill_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='shipt',
        ),
        migrations.AlterField(
            model_name='salebill',
            name='deliveryDate',
            field=models.CharField(default='', max_length=150),
        ),
    ]
