# Generated by Django 4.2.2 on 2023-07-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_remove_salebill_shipt_alter_salebill_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='description',
            field=models.IntegerField(default=1),
        ),
    ]
