# Generated by Django 4.2.2 on 2023-07-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_saleitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
