# Generated by Django 4.2.2 on 2023-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_saleitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
