# Generated by Django 4.2.2 on 2023-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_purchaseitem_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='perprice',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
        ),
    ]
