# Generated by Django 4.2.2 on 2023-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_remove_purchaseitem_stock_purchaseitem_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.FloatField(default=1),
        ),
    ]
